---
- name: Deploy Vanilla Minecraft Server on OpenShift
  hosts: localhost
  gather_facts: no
  roles:
    - role: minecraft-oc-deploy
      vars:
        minecraft_world: "super-fun-world"
        minecraft_image: "itzg/minecraft-server:latest"
        minecraft_memory: "32G"
        minecraft_port: 25565
        minecraft_gamemode: "survival"
        minecraft_difficulty: "normal"
        minecraft_motd: "Hello and welcome to a super fun world!"
        minecraft_eula: true
        minecraft_enable_rcon: true
        minecraft_custom_properties:
          max-players: "20"
          view-distance: "10"
          simulation-distance: "10"
          level-seed: ""
        minecraft_persistent_storage_size: "20Gi"